### ISSUE TITLE
大学周辺の飯屋に詳しくない

### ISSUE THREAD

**Issue by sjntn** [sjntn/daigaku#3]
いわゆる「ワセメシ」の会話に混ざれない

**Comment by sjntn** [comment]
それなりに行った気がするのであと愛川行ったらcloseする

**Comment by wataori** [comment]
https://github.com/sjntn/meiten/blob/master/tokyo.md
愛川チェックついてます

**Comment by sjntn** [comment]
@wataori SORENA
