### ISSUE TITLE
単位を取得するペースが落ちてきてつらい

### ISSUE THREAD

**Issue by sjntn** [sjntn/daigaku#4]

**Comment by arikou** [comment]
![LGTM](http://i.imgur.com/HGyl1Eg.gif)

**Comment by sjntn** [comment]
3/1 成績発表

**Comment by arikou** [comment]
![tiqav](https://img.tiqav.com/kW.jpg)

**Comment by sjntn** [comment]
発表された。そんなに悪くない。
https://github.com/sjntn/daigaku/blob/master/README.md

**Comment by arikou** [comment]
なんだこれ順調じゃねーか...

**Comment by sjntn** [comment]
卒業成功したい

**Comment by arikou** [comment]
![tiqav](https://img.tiqav.com/y.jpg)

**Comment by sjntn** [comment]
取得ペースが戻ったので一旦 close.

**Comment by sjntn** [comment]
絶対に reopen したくない。

**Comment by sjntn** [comment]
操作間違えて一瞬 reopen してしまった...
