### ISSUE TITLE
なんの授業を取れば卒業できるのか

### ISSUE THREAD

**Issue by wataori** [sjntn/daigaku#5]
![2015-09-12 12 37 22](https://cloud.githubusercontent.com/assets/6727837/9829700/17088fac-594b-11e5-842a-1cad5088ab22.png)
コア科目1つとらないといけないのかどうか
朝起きたくない

**Comment by sjntn** [comment]
@wataori コア科目取らなきゃいけない〜、2限とかでもあるんじゃないか

**Comment by wataori** [comment]
いやだ〜〜いやだ〜〜
